<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cacfcb42-23b8-4046-ac3d-4d1d3901b970</elementGuidId>
    <imagePath></imagePath>
    <name>div_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[data-id='\31 58'] .products-slider__product-wrapper</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'products-slider__product-wrapper')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>products-slider__product-wrapper</value>
        <webElementGuid>793a087c-cb5d-47b2-afe2-4037dd107678</webElementGuid>
    </webElementProperties>
</WebElementEntity>