<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4dc05e6b-239a-404f-a731-808bb263e623</elementGuidId>
    <imagePath></imagePath>
    <name>h1_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/h1[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.page-heading</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'page-heading page-heading_h1 page-heading_m-h1')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>page-heading page-heading_h1 page-heading_m-h1</value>
        <webElementGuid>e228438c-fde2-4dd6-9113-56a0ab743248</webElementGuid>
    </webElementProperties>
</WebElementEntity>