<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>15a58f76-24f5-4544-99f0-a75e03fa2313</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_category_podborki</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/nav[1]/div[1]/ul[1]/li[4]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.horizontal-menu__element[href='\/category\/podborki']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'horizontal-menu__element is-link is-root')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>horizontal-menu__element is-link is-root</value>
        <webElementGuid>ea0bf95d-a6a1-4c5d-a93f-a95fe61f2b1d</webElementGuid>
    </webElementProperties>
</WebElementEntity>